version: '2.3'
services:
  orpy18m:
    image: openrave-1804-melodic:v2.0.0
    privileged: true
    build:
      context: .
      args:
        user: ${dUSER}
        group: ${dGROUP}
        uid: ${dUID}
        gid: ${dGID}
        git_username: ${dGIT_USER}
        git_email: ${dGIT_EMAIL}
    user: "${dUID?err}:${dGID?err}"
    runtime: nvidia
    tty: true
    environment:
    - "XAUTHORITY=/tmp/.docker.xauth"
    - "DISPLAY"
    volumes:
    - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
    - "/tmp/.docker.xauth:/tmp/.docker.xauth:rw"
    - "${dDRIVE?err}:/data"
    - "${dWORKSPACE?err}:/home/${dUSER}/workspace"
