version: '2.3'
services:
  workshop:
    image: workshop:v0.0.1
    build:
      context: .
      args:
        user: ${dUSER}
        group: ${dGROUP}
        uid: ${dUID}
        gid: ${dGID}
    user: "${dUID?err}:${dGID?err}"
    runtime: nvidia
    tty: true
    ports:
    - "${dPORT?err}:8888"
    volumes:
    - "${dDRIVE?err}:/data"
    - "${dWORKSPACE?err}:/home/${dUSER}/workspace"
    - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
    - "/tmp/.docker.xauth:/tmp/.docker.xauth:rw"
    environment:
    - "XAUTHORITY=/tmp/.docker.xauth"
    - "DISPLAY"
